/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReviewLogitechMxMaster4RouteImport } from './routes/review-logitech-mx-master-4'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TermosECondicoesRouteImport } from './routes/termos-e-condicoes'
import { Route as Yandex_7b24930530df8f25DothtmlRouteImport } from './routes/yandex_7b24930530df8f25[.]html'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewLogitechMxMaster4Route = ReviewLogitechMxMaster4RouteImport.update({
  id: '/review-logitech-mx-master-4',
  path: '/review-logitech-mx-master-4',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosECondicoesRoute = TermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const Yandex_7b24930530df8f25DothtmlRoute =
  Yandex_7b24930530df8f25DothtmlRouteImport.update({
    id: '/yandex_7b24930530df8f25.html',
    path: '/yandex_7b24930530df8f25.html',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/review-logitech-mx-master-4': typeof ReviewLogitechMxMaster4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos': typeof TermosRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/yandex_7b24930530df8f25.html': typeof Yandex_7b24930530df8f25DothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/review-logitech-mx-master-4': typeof ReviewLogitechMxMaster4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos': typeof TermosRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/yandex_7b24930530df8f25.html': typeof Yandex_7b24930530df8f25DothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/review-logitech-mx-master-4': typeof ReviewLogitechMxMaster4Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/sobre-nos': typeof SobreNosRoute
  '/termos': typeof TermosRoute
  '/termos-e-condicoes': typeof TermosECondicoesRoute
  '/yandex_7b24930530df8f25.html': typeof Yandex_7b24930530df8f25DothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contato'
    | '/fale-conosco'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/review-logitech-mx-master-4'
    | '/sitemap.xml'
    | '/sobre'
    | '/sobre-nos'
    | '/termos'
    | '/termos-e-condicoes'
    | '/yandex_7b24930530df8f25.html'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contato'
    | '/fale-conosco'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/review-logitech-mx-master-4'
    | '/sitemap.xml'
    | '/sobre'
    | '/sobre-nos'
    | '/termos'
    | '/termos-e-condicoes'
    | '/yandex_7b24930530df8f25.html'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contato'
    | '/fale-conosco'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/review-logitech-mx-master-4'
    | '/sitemap.xml'
    | '/sobre'
    | '/sobre-nos'
    | '/termos'
    | '/termos-e-condicoes'
    | '/yandex_7b24930530df8f25.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContatoRoute: typeof ContatoRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReviewLogitechMxMaster4Route: typeof ReviewLogitechMxMaster4Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SobreNosRoute: typeof SobreNosRoute
  TermosRoute: typeof TermosRoute
  TermosECondicoesRoute: typeof TermosECondicoesRoute
  Yandex_7b24930530df8f25DothtmlRoute: typeof Yandex_7b24930530df8f25DothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-logitech-mx-master-4': {
      id: '/review-logitech-mx-master-4'
      path: '/review-logitech-mx-master-4'
      fullPath: '/review-logitech-mx-master-4'
      preLoaderRoute: typeof ReviewLogitechMxMaster4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-e-condicoes': {
      id: '/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof TermosECondicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yandex_7b24930530df8f25.html': {
      id: '/yandex_7b24930530df8f25.html'
      path: '/yandex_7b24930530df8f25.html'
      fullPath: '/yandex_7b24930530df8f25.html'
      preLoaderRoute: typeof Yandex_7b24930530df8f25DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContatoRoute: ContatoRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReviewLogitechMxMaster4Route: ReviewLogitechMxMaster4Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SobreNosRoute: SobreNosRoute,
  TermosRoute: TermosRoute,
  TermosECondicoesRoute: TermosECondicoesRoute,
  Yandex_7b24930530df8f25DothtmlRoute: Yandex_7b24930530df8f25DothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
